name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      - name: "Set up Python"
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -r requirements.txt

      - name: "Install requirements test"
        run: python3 -m pip install -r requirements_test.txt

      - name: "Test"
        run: pytest
